[project]
name = "crispr-off-t-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytorch-lightning==2.5.0.post0",
    "wandb==0.19.1",
]
