label: crispr_bert #crispr_dipoff, r_crispr, deep_cnn,

crispr_bert:
  vocab_size: 256
  hidden_size: 64
  intermediate_size: 2048
  hidden_act: "gelu"
  num_attention_heads: 8
  num_hidden_layers: 6
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  learning_rate: 2e-5

crispr_dipoff:
  vocab_size: 0
  emb_size: 4
  hidden_size: 512
  lstm_layers: 1
  bi_lstm: True
  number_hidder_layers: 2
  dropout_prob: 0.4
  reshape: False
  batch_size": 128
  epochs: 50
  learning_rate: 0.00010

r_crispr:
  learning_rate: 1e-3

deep_cnn:
  learning_rate: 1e-4
