name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39
        continue-on-error: true

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.12
      - uses: pre-commit/action@v3.0.1
